# Generated by Django 5.0.4 on 2026-05-20 18:49

import base.models.authentication
import base.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                        verbose_name="atualizado em",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, default="", verbose_name="descrição")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Drop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                        verbose_name="atualizado em",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, default="", verbose_name="descrição")),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Operador precisa ativar explicitamente antes do lançamento.",
                        verbose_name="ativo",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Banner principal do drop. JPG/JPEG/PNG/WEBP, máximo 10 MB.",
                        null=True,
                        upload_to="drops/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            base.validators.validate_max_image_size,
                        ],
                        verbose_name="imagem de capa",
                    ),
                ),
                (
                    "launch_date",
                    models.DateTimeField(
                        help_text="Data e hora de liberação pública do drop.",
                        verbose_name="data de lançamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "drop",
                "verbose_name_plural": "drops",
                "ordering": ["-launch_date"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("name", models.CharField(max_length=255, verbose_name="Nome completo")),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True, verbose_name="Google ID"
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="URL do avatar (Google)"
                    ),
                ),
                (
                    "is_new_user",
                    models.BooleanField(
                        default=True,
                        help_text="True no primeiro login, False nos logins subsequentes.",
                        verbose_name="É um novo utilizador?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="+",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="+",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilizador",
                "verbose_name_plural": "Utilizadores",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", base.models.authentication.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="e-mail destinatário"),
                ),
                (
                    "template_name",
                    models.CharField(
                        choices=[
                            ("ORDER_PLACED", "Pedido criado"),
                            ("PAYMENT_CONFIRMED", "Pagamento confirmado"),
                            ("ORDER_SHIPPED", "Pedido enviado"),
                            ("PASSWORD_RESET", "Reset de senha"),
                            ("WELCOME", "Boas-vindas"),
                            ("LOW_STOCK_ALERT", "Alerta de estoque baixo"),
                        ],
                        max_length=30,
                        verbose_name="template",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="assunto")),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Variáveis passadas ao template no momento do envio.",
                        verbose_name="contexto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("SENT", "Enviado"),
                            ("FAILED", "Falhou"),
                            ("BOUNCED", "Bounce"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="",
                        help_text="sendgrid | console",
                        max_length=30,
                        verbose_name="provider",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID da mensagem no provider",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="mensagem de erro"),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="enviado em")),
            ],
            options={
                "verbose_name": "log de e-mail",
                "verbose_name_plural": "logs de e-mail",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_email", "template_name"],
                        name="base_emaill_recipie_263e37_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="base_emaill_status_6e5a1a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                        verbose_name="atualizado em",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nome")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("description", models.TextField(verbose_name="descrição")),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="preço regular",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Quando definido, sobrepõe o preço regular.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="preço promocional",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "weight_g",
                    models.PositiveIntegerField(
                        help_text="Peso em gramas, usado no cálculo de frete.",
                        verbose_name="peso (g)",
                    ),
                ),
                (
                    "length_cm",
                    models.PositiveSmallIntegerField(
                        help_text="Comprimento da embalagem em centímetros (frete).",
                        verbose_name="comprimento (cm)",
                    ),
                ),
                (
                    "width_cm",
                    models.PositiveSmallIntegerField(
                        help_text="Largura da embalagem em centímetros (frete).",
                        verbose_name="largura (cm)",
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveSmallIntegerField(
                        help_text="Altura da embalagem em centímetros (frete).",
                        verbose_name="altura (cm)",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="base.category",
                        verbose_name="categoria",
                    ),
                ),
                (
                    "drop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="base.drop",
                        verbose_name="drop",
                    ),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        help_text="JPG/JPEG/PNG/WEBP, máximo 10 MB.",
                        upload_to="images/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            base.validators.validate_max_image_size,
                        ],
                        verbose_name="arquivo",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Imagens com ordem menor aparecem primeiro.",
                        verbose_name="ordem de exibição",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Texto alternativo (alt) e legenda.",
                        max_length=255,
                        verbose_name="descrição",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="MIME type"
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveIntegerField(default=0, verbose_name="tamanho (bytes)"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="base.product",
                        verbose_name="produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "imagem de produto",
                "verbose_name_plural": "imagens de produto",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("P", "P"),
                            ("M", "M"),
                            ("G", "G"),
                            ("GG", "GG"),
                            ("ÚNICO", "Único"),
                        ],
                        max_length=5,
                        verbose_name="tamanho",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="base.product",
                        verbose_name="produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "variação de produto",
                "verbose_name_plural": "variações de produto",
                "ordering": ["size"],
                "unique_together": {("product", "size")},
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "available_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Unidades prontas para venda imediata.",
                        verbose_name="quantidade disponível",
                    ),
                ),
                (
                    "reserved_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Unidades em carrinhos ativos (aguardando checkout).",
                        verbose_name="quantidade reservada",
                    ),
                ),
                (
                    "minimum_quantity",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Limiar para alerta de estoque baixo.",
                        verbose_name="quantidade mínima",
                    ),
                ),
                (
                    "last_movement_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última movimentação em"
                    ),
                ),
                (
                    "variation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="base.productvariation",
                        verbose_name="variação",
                    ),
                ),
            ],
            options={
                "verbose_name": "estoque",
                "verbose_name_plural": "estoques",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["available_quantity"], name="base_stock_availab_35bdae_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrada"),
                            ("OUT", "Saída"),
                            ("RESERVE", "Reserva"),
                            ("RELEASE", "Liberação"),
                            ("ADJUSTMENT", "Ajuste"),
                        ],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Pode ser negativo em ADJUSTMENT.", verbose_name="quantidade"
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="motivo"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="base.productvariation",
                        verbose_name="variação",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimento de estoque",
                "verbose_name_plural": "movimentos de estoque",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["variation", "created_at"], name="base_stockm_variati_578a50_idx"
                    )
                ],
            },
        ),
    ]
